### ISSUE TITLE
Build fails on Humble (Ubuntu 22.04) – multiple dependencies unresolved with install.sh

### ISSUE THREAD

**Issue by furkanpur** [Arena-Rosnav/arena-rosnav#215]
Hello,

I have been trying to set up arena-rosnav on ROS 2 Humble (Ubuntu 22.04) by strictly following the provided install.sh script. Despite multiple clean installations and repeated attempts, I have not been able to get the build to finish successfully using only the installer.

Initially, the build failed with:
`Summary: 0 packages finished [1.19s]
  6 packages failed: actuator_msgs cv_bridge gps_msgs image_geometry pcl_msgs vision_msgs
  6 packages not processed`

When I attempted to manually install some of these dependencies and re-run the build, I encountered further errors:
`Summary: 0 packages finished [2.36s]
12 packages failed: arena_bringup arena_rclpy_mixins gps_tools gpsd_client opencv_tests plan_msgs rviz_utils task_generator_msgs testing unity_msgs vision_msgs_rviz_plugins vision_opencv`

`--- stderr: vision_msgs_rviz_plugins
CMake Error at CMakeLists.txt:62 (add_library):
  Target "vision_msgs_rviz_plugins" links to target "yaml-cpp::yaml-cpp" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?`

It seems that several key dependencies (both upstream packages like cv_bridge, image_geometry, vision_opencv and arena-related packages such as arena_bringup, task_generator_msgs) are not resolving or building properly in Humble through the current workflow.

Could you please confirm if Humble on Ubuntu 22.04 is officially supported, and if there are additional manual steps required beyond the provided install.sh? Any guidance on resolving these dependency issues would be greatly appreciated.

**Comment by furkanpur** [comment]
Additionally, I attempted to build the project inside a Docker container and encountered the same dependency failures during the build. The error trace is as follows:

469.8 Summary: 0 packages finished [1.09s]
469.8   6 packages failed: actuator_msgs cv_bridge gps_msgs image_geometry pcl_msgs vision_msgs
469.8   6 packages not processed

Dockerfile:57

  56 |     ADD install.sh install.sh
  57 | >>> RUN \
  58 | >>> --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
  59 | >>> --mount=target=/var/cache/apt,type=cache,sharing=locked \
  60 | >>> --mount=type=cache,target=/root/.cache/pip \
  61 | >>>     bash -c 'echo -e "\n\n\n\n\n\n\n" | bash install.sh'
  62 |     

ERROR: failed to build: failed to solve: process "/bin/sh -c bash -c 'echo -e \"\\n\\n\\n\\n\\n\\n\\n\" | bash install.sh'" did not complete successfully: exit code: 1

**Comment by alisher-ai** [comment]
I also could not install it. 

@voshch @tuananhroman 
would appreciate any comment or support on the installation.

**Comment by voshch** [comment]
Hey, thanks for your report.
Ubuntu 22.04 is the officially supported platform and we have repeatedly validated the installation.

A potential issue could arise from ros2 humble being sourced in the shell that you run `install.sh` from. This is probably the case if you already have ros2 humble installed and added to your `~/.bashrc`. Comment the `source /opt/ros/humble/setup.bash` line and open a completely new shell, then retry.

> Initially, the build failed with:
> Summary: 0 packages finished [1.19s] 6 packages failed: actuator_msgs cv_bridge gps_msgs image_geometry pcl_msgs vision_msgs 6 packages not processed

The build is not supposed to fail and is likely caused by the aforementioned situation.
Could you provide the build log for those errors?
The sources should exist in `src/deps/` and don't need to be manually installed.


The Dockerfile is currently not supported and not mentioned anywhere in the docs.

Best
VS

**Comment by dvdmc** [comment]
Hi! Let me continue since the issue is still opened and we are having some troubles. I am currently running the install process with a Docker that starts from a fresh Ubuntu 22.04 and install basic packages. As far as I understand, Arena automatic install should work without ROS 2 installed in the system. I found the following errors:
- python3-rosdep needs to be installed. After setting up ROS 2 repositories and install only `rosdep` (not ROS 2), I can advance.
- pyenv is not in path. I added `export PATH="$HOME/.pyenv/bin:$PATH"` after the msg "Installing Python deps...".

Then it reaches a colcon compile step where it outputs:

```bash
sourced arena environment
Using base paths: /root/arena4_ws/src
Using build base: /root/arena4_ws/build
Using install base: /root/arena4_ws/install
Building paths: /root/arena4_ws/src/arena/* /root/arena4_ws/src/deps/*
INDEXING: colcon list --base-paths /root/arena4_ws/src/arena/* /root/arena4_ws/src/deps/*
BUILDING: colcon build --symlink-install --continue-on-error --packages-skip qt_gui_core rqt qt_gui_cpp rqt_gui_cpp --cmake-args '-DPython3_ROOT_DIR=/root/arena4_ws/src/arena/arena-rosnav/.venv -DBUILD_TESTING=OFF' --base-paths /root/arena4_ws/src --build-base /root/arena4_ws/build --install-base /root/arena4_ws/install --packages-select actuator_msgs cv_bridge gps_msgs gps_tools gps_umd gpsd_client image_geometry opencv_tests pcl_msgs vision_msgs vision_msgs_rviz_plugins vision_opencv --paths src/ros2/ament src/ros2/eclipse-cyclonedds src/ros2/eclipse-iceoryx src/ros2/eProsima src/ros2/gazebo-release src/ros2/osrf src/ros2/ros src/ros2/ros2 src/ros2/ros-perception src/ros2/ros-planning src/ros2/ros-tooling src/ros2/ros-visualization
Starting >>> gps_msgs
[1.467s] colcon.colcon_cmake.task.cmake.build ERROR Failed to find the following files:
- /root/arena4_ws/install/ament_cppcheck/share/ament_cppcheck/package.sh
- /root/arena4_ws/install/ament_lint/share/ament_lint/package.sh
- /root/arena4_ws/install/ament_package/share/ament_package/package.sh
- /root/arena4_ws/install/ament_pycodestyle/share/ament_pycodestyle/package.sh
- /root/arena4_ws/install/fastcdr/share/fastcdr/package.sh
- /root/arena4_ws/install/google_benchmark_vendor/share/google_benchmark_vendor/package.sh
- /root/arena4_ws/install/gtest_vendor/share/gtest_vendor/package.sh
- /root/arena4_ws/install/osrf_pycommon/share/osrf_pycommon/package.sh
- /root/arena4_ws/install/osrf_testing_tools_cpp/share/osrf_testing_tools_cpp/package.sh
- /root/arena4_ws/install/ament_cmake_core/share/ament_cmake_core/package.sh
- /root/arena4_ws/install/ament_flake8/share/ament_flake8/package.sh
- /root/arena4_ws/install/gmock_vendor/share/gmock_vendor/package.sh
- /root/arena4_ws/install/ament_cmake_export_definitions/share/ament_cmake_export_definitions/package.sh
- /root/arena4_ws/install/ament_cmake_export_include_directories/share/ament_cmake_export_include_directories/package.sh
- /root/arena4_ws/install/ament_cmake_export_libraries/share/ament_cmake_export_libraries/package.sh
- /root/arena4_ws/install/ament_cmake_export_link_flags/share/ament_cmake_export_link_flags/package.sh
- /root/arena4_ws/install/ament_cmake_include_directories/share/ament_cmake_include_directories/package.sh
- /root/arena4_ws/install/ament_cmake_libraries/share/ament_cmake_libraries/package.sh
- /root/arena4_ws/install/ament_cmake_python/share/ament_cmake_python/package.sh
- /root/arena4_ws/install/ament_cmake_version/share/ament_cmake_version/package.sh
- /root/arena4_ws/install/ament_pep257/share/ament_pep257/package.sh
- /root/arena4_ws/install/test_interface_files/share/test_interface_files/package.sh
- /root/arena4_ws/install/ament_cmake_export_dependencies/share/ament_cmake_export_dependencies/package.sh
- /root/arena4_ws/install/ament_cmake_export_interfaces/share/ament_cmake_export_interfaces/package.sh
- /root/arena4_ws/install/ament_cmake_export_targets/share/ament_cmake_export_targets/package.sh
- /root/arena4_ws/install/ament_cmake_target_dependencies/share/ament_cmake_target_dependencies/package.sh
- /root/arena4_ws/install/ament_cmake_test/share/ament_cmake_test/package.sh
- /root/arena4_ws/install/ament_copyright/share/ament_copyright/package.sh
- /root/arena4_ws/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.sh
- /root/arena4_ws/install/ament_cmake_gtest/share/ament_cmake_gtest/package.sh
- /root/arena4_ws/install/ament_cmake_pytest/share/ament_cmake_pytest/package.sh
- /root/arena4_ws/install/ament_cpplint/share/ament_cpplint/package.sh
- /root/arena4_ws/install/ament_index_python/share/ament_index_python/package.sh
- /root/arena4_ws/install/ament_lint_auto/share/ament_lint_auto/package.sh
- /root/arena4_ws/install/ament_lint_cmake/share/ament_lint_cmake/package.sh
- /root/arena4_ws/install/ament_xmllint/share/ament_xmllint/package.sh
- /root/arena4_ws/install/domain_coordinator/share/domain_coordinator/package.sh
- /root/arena4_ws/install/ament_cmake_gen_version_h/share/ament_cmake_gen_version_h/package.sh
- /root/arena4_ws/install/ament_cmake_gmock/share/ament_cmake_gmock/package.sh
- /root/arena4_ws/install/ament_cmake_lint_cmake/share/ament_cmake_lint_cmake/package.sh
- /root/arena4_ws/install/launch/share/launch/package.sh
- /root/arena4_ws/install/rosidl_cli/share/rosidl_cli/package.sh
- /root/arena4_ws/install/rpyutils/share/rpyutils/package.sh
- /root/arena4_ws/install/ament_cmake/share/ament_cmake/package.sh
- /root/arena4_ws/install/ament_cmake_copyright/share/ament_cmake_copyright/package.sh
- /root/arena4_ws/install/launch_xml/share/launch_xml/package.sh
- /root/arena4_ws/install/launch_yaml/share/launch_yaml/package.sh
- /root/arena4_ws/install/ament_cmake_cppcheck/share/ament_cmake_cppcheck/package.sh
- /root/arena4_ws/install/ament_cmake_cpplint/share/ament_cmake_cpplint/package.sh
- /root/arena4_ws/install/ament_cmake_flake8/share/ament_cmake_flake8/package.sh
- /root/arena4_ws/install/ament_cmake_pep257/share/ament_cmake_pep257/package.sh
- /root/arena4_ws/install/ament_cmake_xmllint/share/ament_cmake_xmllint/package.sh
- /root/arena4_ws/install/launch_testing/share/launch_testing/package.sh
- /root/arena4_ws/install/uncrustify_vendor/share/uncrustify_vendor/package.sh
- /root/arena4_ws/install/ament_uncrustify/share/ament_uncrustify/package.sh
- /root/arena4_ws/install/ament_cmake_uncrustify/share/ament_cmake_uncrustify/package.sh
- /root/arena4_ws/install/ament_lint_common/share/ament_lint_common/package.sh
- /root/arena4_ws/install/ament_cmake_ros/share/ament_cmake_ros/package.sh
- /root/arena4_ws/install/fastrtps_cmake_module/share/fastrtps_cmake_module/package.sh
- /root/arena4_ws/install/mimick_vendor/share/mimick_vendor/package.sh
- /root/arena4_ws/install/performance_test_fixture/share/performance_test_fixture/package.sh
- /root/arena4_ws/install/python_cmake_module/share/python_cmake_module/package.sh
- /root/arena4_ws/install/rosidl_adapter/share/rosidl_adapter/package.sh
- /root/arena4_ws/install/rosidl_typesupport_interface/share/rosidl_typesupport_interface/package.sh
- /root/arena4_ws/install/launch_testing_ament_cmake/share/launch_testing_ament_cmake/package.sh
- /root/arena4_ws/install/rosidl_parser/share/rosidl_parser/package.sh
- /root/arena4_ws/install/rcutils/share/rcutils/package.sh
- /root/arena4_ws/install/rosidl_cmake/share/rosidl_cmake/package.sh
- /root/arena4_ws/install/rcpputils/share/rcpputils/package.sh
- /root/arena4_ws/install/rosidl_generator_c/share/rosidl_generator_c/package.sh
- /root/arena4_ws/install/rosidl_runtime_c/share/rosidl_runtime_c/package.sh
- /root/arena4_ws/install/rmw/share/rmw/package.sh
- /root/arena4_ws/install/rosidl_runtime_cpp/share/rosidl_runtime_cpp/package.sh
- /root/arena4_ws/install/rosidl_typesupport_introspection_c/share/rosidl_typesupport_introspection_c/package.sh
- /root/arena4_ws/install/rosidl_generator_cpp/share/rosidl_generator_cpp/package.sh
- /root/arena4_ws/install/rosidl_typesupport_introspection_cpp/share/rosidl_typesupport_introspection_cpp/package.sh
- /root/arena4_ws/install/rosidl_typesupport_fastrtps_cpp/share/rosidl_typesupport_fastrtps_cpp/package.sh
- /root/arena4_ws/install/rosidl_typesupport_fastrtps_c/share/rosidl_typesupport_fastrtps_c/package.sh
- /root/arena4_ws/install/rosidl_typesupport_c/share/rosidl_typesupport_c/package.sh
- /root/arena4_ws/install/rosidl_generator_py/share/rosidl_generator_py/package.sh
- /root/arena4_ws/install/rosidl_typesupport_cpp/share/rosidl_typesupport_cpp/package.sh
- /root/arena4_ws/install/rosidl_default_generators/share/rosidl_default_generators/package.sh
- /root/arena4_ws/install/rosidl_default_runtime/share/rosidl_default_runtime/package.sh
- /root/arena4_ws/install/builtin_interfaces/share/builtin_interfaces/package.sh
- /root/arena4_ws/install/std_msgs/share/std_msgs/package.sh
Check that the following packages have been built:
- ament_cppcheck
- ament_lint
- ament_package
- ament_pycodestyle
- fastcdr
- google_benchmark_vendor
- gtest_vendor
- osrf_pycommon
- osrf_testing_tools_cpp
- ament_cmake_core
- ament_flake8
- gmock_vendor
- ament_cmake_export_definitions
- ament_cmake_export_include_directories
- ament_cmake_export_libraries
- ament_cmake_export_link_flags
- ament_cmake_include_directories
- ament_cmake_libraries
- ament_cmake_python
- ament_cmake_version
- ament_pep257
- test_interface_files
- ament_cmake_export_dependencies
- ament_cmake_export_interfaces
- ament_cmake_export_targets
- ament_cmake_target_dependencies
- ament_cmake_test
- ament_copyright
- ament_cmake_google_benchmark
- ament_cmake_gtest
- ament_cmake_pytest
- ament_cpplint
- ament_index_python
- ament_lint_auto
- ament_lint_cmake
- ament_xmllint
- domain_coordinator
- ament_cmake_gen_version_h
- ament_cmake_gmock
- ament_cmake_lint_cmake
- launch
- rosidl_cli
- rpyutils
- ament_cmake
- ament_cmake_copyright
- launch_xml
- launch_yaml
- ament_cmake_cppcheck
- ament_cmake_cpplint
- ament_cmake_flake8
- ament_cmake_pep257
- ament_cmake_xmllint
- launch_testing
- uncrustify_vendor
- ament_uncrustify
- ament_cmake_uncrustify
- ament_lint_common
- ament_cmake_ros
- fastrtps_cmake_module
- mimick_vendor
- performance_test_fixture
- python_cmake_module
- rosidl_adapter
- rosidl_typesupport_interface
- launch_testing_ament_cmake
- rosidl_parser
- rcutils
- rosidl_cmake
- rcpputils
- rosidl_generator_c
- rosidl_runtime_c
- rmw
- rosidl_runtime_cpp
- rosidl_typesupport_introspection_c
- rosidl_generator_cpp
- rosidl_typesupport_introspection_cpp
- rosidl_typesupport_fastrtps_cpp
- rosidl_typesupport_fastrtps_c
- rosidl_typesupport_c
- rosidl_generator_py
- rosidl_typesupport_cpp
- rosidl_default_generators
- rosidl_default_runtime
- builtin_interfaces
- std_msgs
Failed   <<< gps_msgs [0.03s, exited with code 1]
Starting >>> cv_bridge
... (the same for all the packages, then:)
6 packages failed: actuator_msgs cv_bridge gps_msgs image_geometry pcl_msgs vision_msgs
```


Could we work it from here? You can check the `Dockerfile` and my modified `install.sh` [here](https://github.com/dvdmc/arena-rosnav-docker)

**Comment by crcz25** [comment]
Hi all,

I first tried to build the project locally, but the installation failed with the following missing packages:

```
[2.144s] colcon.colcon_cmake.task.cmake.build ERROR Failed to find the following files:
- /home/crcz/arena4_ws/install/ament_pycodestyle/share/ament_pycodestyle/package.sh
- /home/crcz/arena4_ws/install/fastcdr/share/fastcdr/package.sh
- /home/crcz/arena4_ws/install/google_benchmark_vendor/share/google_benchmark_vendor/package.sh
- /home/crcz/arena4_ws/install/gtest_vendor/share/gtest_vendor/package.sh
- /home/crcz/arena4_ws/install/osrf_testing_tools_cpp/share/osrf_testing_tools_cpp/package.sh
- /home/crcz/arena4_ws/install/gmock_vendor/share/gmock_vendor/package.sh
- /home/crcz/arena4_ws/install/test_interface_files/share/test_interface_files/package.sh
- /home/crcz/arena4_ws/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.sh
- /home/crcz/arena4_ws/install/mimick_vendor/share/mimick_vendor/package.sh
- /home/crcz/arena4_ws/install/performance_test_fixture/share/performance_test_fixture/package.sh
Check that the following packages have been built:
- ament_pycodestyle
- fastcdr
- google_benchmark_vendor
- gtest_vendor
- osrf_testing_tools_cpp
- gmock_vendor
- test_interface_files
- ament_cmake_google_benchmark
- mimick_vendor
- performance_test_fixture
Failed   <<< pcl_msgs [0.01s, exited with code 1]

Summary: 0 packages finished [2.02s]
  6 packages failed: actuator_msgs cv_bridge gps_msgs image_geometry pcl_msgs vision_msgs
  6 packages not processed
```

I also tried modifying the install.sh script to source ROS 2 differently (both from my global Humble installation and from a from-source build), but the issue persists. I’ve attached the log of my local install attempt for reference, [log.txt](https://github.com/user-attachments/files/22768671/log.txt).

Out of curiosity, I also ran the Docker build to compare behavior. As mentioned earlier in this thread, I understand Docker support might not yet be complete. However, the same packages from the list before are not found, and the Docker build fails.

**Comment by voshch** [comment]
Yeah just found a really stupid mistake, the dev repo was set as upstream instead of the stable repo.
Fixed in https://github.com/Arena-Rosnav/arena-rosnav/commit/642aa644730b81e5160603a41cbf81d7004b26d3.

> Could we work it from here? You can check the Dockerfile and my modified install.sh [here](https://github.com/dvdmc/arena-rosnav-docker)

Yes, this looks good in general. I'll rework the installer to work with the noninteractive build as well, so that the base system is built into the image. I'll get back to you.

> I also tried modifying the install.sh script to source ROS 2 differently (both from my global Humble installation and from a from-source build), but the issue persists. I’ve attached the log of my local install attempt for reference, [log.txt](https://github.com/user-attachments/files/22768671/log.txt).

Thanks for your log. This should also be fixed with the correct upstream. Let me know.

**Comment by crcz25** [comment]
Hi,

I tried running the installation again after the fix, but it still fails. Here’s a summary of what I’m seeing in the new log (attached as  [log.txt](https://github.com/user-attachments/files/22879813/log.txt)  too ). The script completes most setup steps, but several repositories fail to resolve via rosdep and the build process then also fails on missing packages. Some examples below:

```
arena_bringup: Cannot locate rosdep definition for [ament_python]
task_generator: Cannot locate rosdep definition for [${PROJECT_NAME}_msgs]
```

```
nav2_util: Could not find a package configuration file provided by "nav2_msgs"
turtlebot4_ignition_bringup: Could not find "ros_ign_interfaces"
```

UPDATE: Realized that a vpn was giving issues with the network. This is the new log with mostly nav2 packages missing.

[log.txt](https://github.com/user-attachments/files/22880539/log.txt)

**Comment by abdelzaro** [comment]
@crcz25 I had the same issue but just did this to fix it: 
sudo apt update
sudo apt install -y python3-rosdep2
sudo rosdep init
rosdep update

**Comment by lsm1041321457** [comment]
also had same problem
