### ISSUE TITLE
About the connection of Arena-rosnav

### ISSUE THREAD

**Issue by AbelSyx** [Arena-Rosnav/arena-rosnav#40]
Hi, it's grateful for your work!
I want to know the connection between [ignc-research/arena-rosnav](https://github.com/ignc-research/arena-rosnav) and this code. Is this an updated version of the original code? 
In the past few weeks, I have been learning from the [ignc-research/arena-rosnav](https://github.com/ignc-research/arena-rosnav) and encountered some questions. I wonder if I can get answers in this community?

**Comment by ReykCS** [comment]
Hey @AbelSyx ,
this organization contains the newest version of [ignc-research/arena-rosnav](https://github.com/ignc-research/arena-rosnav). We restructured the whole project, refactored a lot and removed unused, deprecated and just bad code. Overall, the new structure is more modular and allows faster integration of new simulators, new robots and new planners. Furthermore, some parts of the infrastructure are now usable in combination with other projects, like the [arena-simulation-setup](https://github.com/Arena-Rosnav/arena-simulation-setup) package, which contains worlds, maps and robots and can now be used independently without the overhead of the whole structure.
In general, we made Arena-Rosnav more accessible and more modular. It is now way easier to install and to use.
If you have any questions, feel free to ask them here.

**Comment by AbelSyx** [comment]
Thank you for your reply. I tried to install and compile the new version of arena-rosnav, and found it easier than the old version. I will learn on this basis and look forward to communicating with you!

**Comment by AbelSyx** [comment]
Hey @ReykCS ,
I tried to use `start_training.launch` for Multiprocessed training, and modified the `n_envs:5` in `training_config.yaml` file. The terminal shows that each environment is training normally, as shown in the following figure.
![image](https://user-images.githubusercontent.com/50324194/220659594-434300dc-6b76-4d3e-b895-9fa9075491eb.png)
However, when I used `visualization_training.launch` to visualize the training environment, I found that there are some errors in TF Transform. Is this caused by my incorrect setting?
![image](https://user-images.githubusercontent.com/50324194/220666674-9eed7340-50d6-4288-8cd6-310fd420018a.png)

**Comment by ReykCS** [comment]
Hey @AbelSyx ,

these errors are not caused by your setup and are indeed some bugs in the code. I just pushed a commit, which should fix the issue. However, since we are not using the tf topic for training, it should be not effected by this and should work as expected.

Thanks for pointing this issue out!

**Comment by AbelSyx** [comment]
Okay, thank you for your reply!

**Comment by CAI23sbP** [comment]
Oh! here is similar issue in this script!
Hi @ReykCS.
I launched `visualization_training.launch` that launch pkg is not solved above issue. but there is no "rviz_LP"  file in rviz folder. So i added some topics to visualize in `default.rviz`. you can see that like this.
![Screenshot from 2023-02-24 17-19-28](https://user-images.githubusercontent.com/108871750/221128076-e6686acb-f2d6-404f-987c-1f92768d1c34.png)
Did it work right?. Could you check this?

**Comment by ReykCS** [comment]
Hey @CAI23sbP ,
the nav_LP is missing at the moment, you are correct. I'm sorry for this. 
For now, this means one should start rviz manually and add the topics by hand. What you did looks really good so far and should work.
